### PR TITLE
#680 Redesign of cta panels

### PR DESCRIPTION
**Pull request by pstenstrm**

### CODE REVIEW

**Comment by pstenstrm** [comment]
justarrived680

**Comment by buren** [comment]
I really like the colours of the three sections! :)

_Personal opinion_: I think though on desktop that its a bit to much space between the texts. Perhaps would look better to have them in three columns (full-width within the container) and then on smaller tablets and on phones we could have them exactly like in your screenshot.

Thanks again @pstenstrm 😍

**Comment by buren** [comment]
@pstenstrm what do you think about having the 3-sections in 3-columns on desktop and then on smaller devices have them in 1-column?

cc @camillaryd

**Comment by pstenstrm** [comment]
The sections go into 3 columns at the 768px breakpoint.

This is how it looks like in desktop:
screen shot 2016-08-10 at 15 03 00

**Comment by buren** [comment]
👍 Looks great!

I'll go ahead and merge this.

@pstenstrm ❤️

**Comment by buren** [comment]
screen shot 2016-08-10 at 16 53 37

❤️ ❤️ ❤️

**Comment by pstenstrm** [comment]
Yep, that's the balance I like to keep ✂️

**Comment by buren** [comment]
> Yep, that's the balance I like to keep ✂️

💯 x 👍

**Pull request merged**
