### PR TITLE
Issue/684

### PR DESCRIPTION
**Pull request by pstenstrm**
There was a few additional places where dark hot pink was used as a background color for white text. I changed those places to cerice as well. Any dark hot pink details and texts remains dark hot pink.

### CODE REVIEW

**Comment by buren** [comment]
Could you perhaps provide a screenshot for comparison? :) 

cc @camillaryd, what do you think about the new color code?

**Comment by pstenstrm** [comment]
Wherever there used to be text on dark hot pink it is now cerice, one panel is berry.
justarrived684

Small details like the left border on chat entrances or active tab remains dark hot pink.
justarrived-job684
justarrived-candidate684

**Comment by buren** [comment]
@pstenstrm awesome! Thanks for the screenshots!

@camillaryd what are your thoughts on the above ☝️? :)

**Comment by pstenstrm** [comment]
I've changed the `.pink` classname to `.primary`. The `$pink` variable remains dark hot pink while everywhere the class was used the color is now cerice. I didn't want to name the class `.cerice` to avoid having to change it again if the color changes, but it's also inconsistent with the `.blue`, and `.dark` classnames that we still have.

**Comment by buren** [comment]
:+1: for changing `pink` => `primary`.

How do you think we should rename `blue` and `dark`? `secondary` and... ¯\_(ツ)_/¯

**Comment by pstenstrm** [comment]
`secondary` would be good instead of `dark`. `blue` is only used once, so there's really no red thread to follow, but it's also less of a problem.

**Comment by buren** [comment]
Seems like @camillaryd 👍 this :) https://github.com/justarrived/just-match-frontend/issues/684#issuecomment-232157654

I'm also 👍 for merge :) @pstenstrm could you fix the merge conflict and then you can merge? You have commits rights now if I'm not mistaken 😄

**Comment by buren** [comment]
🎉

**Pull request merged**
